server:
  tomcat:
    max-threads: 2
#    min-spare-threads: 1
#    accept-count: 1
#    max-connections: 1

spring:
  datasource:
    url: jdbc:mysql://mysql.public:3306/performance_test?useSSL=false&characterEncoding=utf8
    username: root
    password: 1234
  redis:
    url: redis://redis.public:6379
    lettuce:
      pool:
        min-idle: 4
  cache:
    redis:
      time-to-live: 10m

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
